version: "3"


networks:
  rssforever:


# ---------------------------------------- nginx ---------------------------------------- #
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/nginx.sh:/nginx.sh
      - ./nginx/vhost:/etc/nginx/conf.d/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - PROTOCOL=${PROTOCOL}
      - RSS_DOMAIN=${RSS_DOMAIN}
      - RSS_DOAMIN_CERT=${RSS_DOAMIN_CERT}
      - RSS_DOMAIN_KEY=${RSS_DOMAIN_KEY}
      - RSSHUB_DOMAIN=${RSSHUB_DOMAIN}
      - RSSHUB_DOAMIN_CERT=${RSSHUB_DOAMIN_CERT}
      - RSSHUB_DOMAIN_KEY=${RSSHUB_DOMAIN_KEY}
    networks:
      - rssforever
    depends_on:
      - service.rss
      - rsshub
    command: ["sh", "-c", "/nginx.sh"]


# ---------------------------------------- ttrss ---------------------------------------- #
  freshrss.db:
    image: postgres:12-alpine
    # container_name: freshrss.db
    hostname: freshrss.db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-freshrss}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-freshrss}
      POSTGRES_DB: ${POSTGRES_DB:-freshrss}
    networks:
      - rssforever

  service.rss:
    image: freshrss/freshrss:${FRESHRSS_X86_VERSION}
    # container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    depends_on:
      - freshrss.db
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: Asia/Shanghai
    networks:
      - rssforever


# ---------------------------------------- rsshub ---------------------------------------- #
  rsshub:
    image: diygod/rsshub
    restart: always
    ports:
      - 1200:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
    depends_on:
      - redis
      - browserless
    networks:
      - rssforever
    

  browserless:
    image: browserless/chrome
    restart: always
    networks:
      - rssforever


  redis:
    image: redis:alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./rsshub/redis-data:/data
    networks:
      - rssforever
    

# ---------------------------------------- watchtower ---------------------------------------- #
# 每天早上 10 点定时更新 RSSHub , 如无需可注释或删除本段.
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 10 * * *
    restart: always
    command: rssforever_acme-1 rssforever_watchtower_1 rssforever_rsshub_1 rssforever_redis_1 rssforever_browserless_1 rssforever_acme_1 rssforever-watchtower-1 rssforever_rsshub-1 rssforever_redis-1 rssforever_browserless-1
    networks:
      - rssforever

