version: "3"

networks:
  rssforever:

# ---------------------------------------- nginx ---------------------------------------- #
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/nginx.sh:/nginx.sh
      - ./nginx/vhost:/etc/nginx/conf.d/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - PROTOCOL=${PROTOCOL}
      - RSS_DOMAIN=${RSS_DOMAIN}
      - RSS_DOAMIN_CERT=${RSS_DOAMIN_CERT}
      - RSS_DOMAIN_KEY=${RSS_DOMAIN_KEY}
      - RSSHUB_DOMAIN=${RSSHUB_DOMAIN}
      - RSSHUB_DOAMIN_CERT=${RSSHUB_DOAMIN_CERT}
      - RSSHUB_DOMAIN_KEY=${RSSHUB_DOMAIN_KEY}
    networks:
      - rssforever
    depends_on:
      - service.rss
    command: ["sh", "-c", "/nginx.sh"]

# ---------------------------------------- rss ---------------------------------------- #
  service.rss:
    image: ${FRESHRSS_IMAGE}:${FRESHRSS_VERSION}
    restart: always
    depends_on:
      - db
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: Asia/Shanghai
    networks:
      - rssforever

  db:
    image: postgres:${FRESHRSS_DB_VERSION}
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-freshrss}
      POSTGRES_DB: freshrss
    networks:
      - rssforever

# ---------------------------------------- acme ---------------------------------------- #
  acme:
    image: neilpang/acme.sh:latest
    volumes:
      - ./acme:/conf
      - ./nginx/ssl:/ssl
    restart: always
    network_mode: host
    command: ["sh", "-c", "/conf/start.sh"]
